name: Scheduled Python Script

on:
  schedule:
    - cron: '*/10 * * * *'  # This will run the script every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install any other dependencies if needed
          # pip install requests

      - name: Run Python script
        run: python script.py
